### ISSUE TITLE
No sfx audio on PPC64

### ISSUE THREAD

**Issue by Link4Electronics** [GaryOderNichts/Shipwright#21]
Hello Gary, I hope everything is okay.
Running Debian sid PPC64 on a PowerMac G5 and having some issues with Shipwright and 2Ship2Harkinian. I've already reported [issue](https://github.com/HarbourMasters/Shipwright/issues/4513) and [issue](https://github.com/HarbourMasters/2ship2harkinian/issues/802), but since you ported it to the WiiU, I thought I'd talk to you directly. I wonder if you have any idea why these issues like no SFX happen on PPC 64bits?

Best regards and have a good week,
Link.

**Comment by GaryOderNichts** [comment]
Note that this repo is for Wii U specific issues. I'm gonna close this and mention some things in the original issues.
